// Auto-generated by generate_complex_pattern_sv.py
// RV32I Complex LED Pattern - Memory Initialization
//
// Total instructions: 83
// Program size: 332 bytes
//
// Pattern modes:
//   Mode 0: Binary counter (0→15, 16 iterations)
//   Mode 1: Knight Rider (1→2→4→8→4→2→1, 30 iterations)
//   Mode 2: Blink all (0xF ↔ 0x0, 20 iterations)
//   Mode 3: Alternating (0x5 ↔ 0xA, 50 iterations)
//
// LED MMIO address: 0x0000_407C
// Delay per iteration: 5M cycles (40ms @ 125MHz)

task load_complex_pattern_program();
    $display("  Loading 83-instruction complex LED pattern program...");
    $display("  Program size: 83 instructions (332 bytes)", 83, 332);

    write_insn_mem(11'h000, 32'h000047B7);  // Setup: LED address
    write_insn_mem(11'h001, 32'h07C78813);
    write_insn_mem(11'h002, 32'h00000113);
    write_insn_mem(11'h003, 32'h000002B7);
    write_insn_mem(11'h004, 32'h3E828213);
    write_insn_mem(11'h005, 32'h00000593);
    write_insn_mem(11'h006, 32'h00B10663);
    write_insn_mem(11'h007, 32'h00100593);
    write_insn_mem(11'h008, 32'h02B10663);
    write_insn_mem(11'h009, 32'h00200593);
    write_insn_mem(11'h00A, 32'h04B10A63);  // Mode dispatch
    write_insn_mem(11'h00B, 32'h00500093);
    write_insn_mem(11'h00C, 32'h03200913);
    write_insn_mem(11'h00D, 32'h00182023);
    write_insn_mem(11'h00E, 32'h00028213);
    write_insn_mem(11'h00F, 32'h38800193);
    write_insn_mem(11'h010, 32'hFFF18193);
    write_insn_mem(11'h011, 32'hFE019EE3);
    write_insn_mem(11'h012, 32'hFFF20213);
    write_insn_mem(11'h013, 32'hFE0218E3);
    write_insn_mem(11'h014, 32'h00F0C093);  // Mode 3: Alternating pattern
    write_insn_mem(11'h015, 32'hFFF90913);
    write_insn_mem(11'h016, 32'hFC091CE3);
    write_insn_mem(11'h017, 32'h00110113);
    write_insn_mem(11'h018, 32'h00400593);
    write_insn_mem(11'h019, 32'hFAB146E3);
    write_insn_mem(11'h01A, 32'h00000113);
    write_insn_mem(11'h01B, 32'hFA5FF06F);
    write_insn_mem(11'h01C, 32'h00000093);
    write_insn_mem(11'h01D, 32'h01000913);
    write_insn_mem(11'h01E, 32'h00182023);  // Mode 3: Alternating pattern
    write_insn_mem(11'h01F, 32'h00028213);
    write_insn_mem(11'h020, 32'h38800193);
    write_insn_mem(11'h021, 32'hFFF18193);
    write_insn_mem(11'h022, 32'hFE019EE3);
    write_insn_mem(11'h023, 32'hFFF20213);
    write_insn_mem(11'h024, 32'hFE0218E3);
    write_insn_mem(11'h025, 32'h00108093);
    write_insn_mem(11'h026, 32'h00F0F093);
    write_insn_mem(11'h027, 32'hFFF90913);
    write_insn_mem(11'h028, 32'hFC091AE3);  // Mode 0: Binary counter
    write_insn_mem(11'h029, 32'h00110113);
    write_insn_mem(11'h02A, 32'hF69FF06F);
    write_insn_mem(11'h02B, 32'h00100093);
    write_insn_mem(11'h02C, 32'h01E00913);
    write_insn_mem(11'h02D, 32'h00100513);
    write_insn_mem(11'h02E, 32'h00182023);
    write_insn_mem(11'h02F, 32'h00028213);
    write_insn_mem(11'h030, 32'h38800193);
    write_insn_mem(11'h031, 32'hFFF18193);
    write_insn_mem(11'h032, 32'hFE019EE3);  // Mode 0: Binary counter
    write_insn_mem(11'h033, 32'hFFF20213);
    write_insn_mem(11'h034, 32'hFE0218E3);
    write_insn_mem(11'h035, 32'h00100593);
    write_insn_mem(11'h036, 32'h00B50663);
    write_insn_mem(11'h037, 32'h0010D093);
    write_insn_mem(11'h038, 32'h00100593);
    write_insn_mem(11'h039, 32'h00B09A63);
    write_insn_mem(11'h03A, 32'h00100513);
    write_insn_mem(11'h03B, 32'h0100006F);
    write_insn_mem(11'h03C, 32'h00109093);  // Mode 1: Knight Rider
    write_insn_mem(11'h03D, 32'h00800593);
    write_insn_mem(11'h03E, 32'h00B09463);
    write_insn_mem(11'h03F, 32'hFFF00513);
    write_insn_mem(11'h040, 32'hFFF90913);
    write_insn_mem(11'h041, 32'hFA0918E3);
    write_insn_mem(11'h042, 32'h00110113);
    write_insn_mem(11'h043, 32'hF05FF06F);
    write_insn_mem(11'h044, 32'h00F00093);
    write_insn_mem(11'h045, 32'h01400913);
    write_insn_mem(11'h046, 32'h00182023);  // Mode 2: Blink all
    write_insn_mem(11'h047, 32'h00028213);
    write_insn_mem(11'h048, 32'h00020213);
    write_insn_mem(11'h049, 32'h38800193);
    write_insn_mem(11'h04A, 32'hFFF18193);
    write_insn_mem(11'h04B, 32'hFE019EE3);
    write_insn_mem(11'h04C, 32'hFFF20213);
    write_insn_mem(11'h04D, 32'hFE0218E3);
    write_insn_mem(11'h04E, 32'h00F0C093);
    write_insn_mem(11'h04F, 32'hFFF90913);
    write_insn_mem(11'h050, 32'hFC091AE3);  // Mode 2: Blink all
    write_insn_mem(11'h051, 32'h00110113);
    write_insn_mem(11'h052, 32'hEC9FF06F);

    $display("  Program loaded successfully");
endtask

// Helper task: Write instruction to memory using debug interface
task write_insn_mem(input logic [10:0] word_addr, input logic [31:0] data);
    // Use the debug memory write interface
    write_debug_mem(word_addr, data);
endtask
