// Auto-generated by generate_minimal_led_test.py
// RV32I MINIMAL LED Test - Memory Initialization
//
// Total instructions: 13
// Program size: 52 bytes
// Configuration: 6 LED writes, 10 cycles/write
//
// Test purpose: Verify LED MMIO functionality
// Expected: Sequential writes (1Å®2Å®3Å®4Å®5Å®6)
// LED MMIO address: 0x0000_407C
// Simulation time needed: ~0.48É s

// Instruction memory initialization (to be included in test task)
write_debug_mem(11'h000, 32'h000047B7);
write_debug_mem(11'h001, 32'h07C78813);
write_debug_mem(11'h002, 32'h00100093);
write_debug_mem(11'h003, 32'h00600913);
write_debug_mem(11'h004, 32'h00A00293);
write_debug_mem(11'h005, 32'h00182023);
write_debug_mem(11'h006, 32'h00028193);
write_debug_mem(11'h007, 32'hFFF18193);
write_debug_mem(11'h008, 32'hFE019EE3);
write_debug_mem(11'h009, 32'h00108093);
write_debug_mem(11'h00A, 32'hFFF90913);
write_debug_mem(11'h00B, 32'hFE0912E3);
write_debug_mem(11'h00C, 32'h00100073);
