// Auto-generated by generate_fast_pattern_sv.py
// RV32I FAST Complex LED Pattern - Memory Initialization
//
// Total instructions: 59
// Program size: 236 bytes
// Mode: ULTRA-FAST SIMULATION (10 cycles/iteration = ~80ns @ 125MHz)
//
// Pattern modes (6 iterations each):
//   Mode 0: Binary counter (1→2→3→4→5→6)
//   Mode 1: Knight Rider (1→2→4→8→4→2)
//   Mode 2: Blink all (0xF ↔ 0x0, 6 toggles)
//   Mode 3: Alternating (0x5 ↔ 0xA, 6 toggles)
//
// LED MMIO address: 0x0000_407C
// Total pattern changes: 24 (4 modes × 6 iterations)
// Simulation time needed: ~2μs for full cycle

// Instruction memory initialization (to be included in test task)
write_debug_mem(11'h000, 32'h000047B7);  // Setup: LED address
write_debug_mem(11'h001, 32'h07C78813);
write_debug_mem(11'h002, 32'h00000113);
write_debug_mem(11'h003, 32'h00A00293);
write_debug_mem(11'h004, 32'h00000593);
write_debug_mem(11'h005, 32'h04B10663);
write_debug_mem(11'h006, 32'h00100593);
write_debug_mem(11'h007, 32'h06B10A63);
write_debug_mem(11'h008, 32'h00200593);
write_debug_mem(11'h009, 32'h08B10E63);
write_debug_mem(11'h00A, 32'h00500093);  // Mode 3: Alternating pattern
write_debug_mem(11'h00B, 32'h00600913);
write_debug_mem(11'h00C, 32'h00182023);
write_debug_mem(11'h00D, 32'h00028193);
write_debug_mem(11'h00E, 32'hFFF18193);
write_debug_mem(11'h00F, 32'hFE019EE3);
write_debug_mem(11'h010, 32'h00F0C093);
write_debug_mem(11'h011, 32'hFFF90913);
write_debug_mem(11'h012, 32'hFE0912E3);
write_debug_mem(11'h013, 32'h00110113);
write_debug_mem(11'h014, 32'h00400593);
write_debug_mem(11'h015, 32'hFAB14CE3);
write_debug_mem(11'h016, 32'h00000113);
write_debug_mem(11'h017, 32'hFB1FF06F);
write_debug_mem(11'h018, 32'h00100093);  // Mode 0: Binary counter
write_debug_mem(11'h019, 32'h00600913);
write_debug_mem(11'h01A, 32'h00182023);
write_debug_mem(11'h01B, 32'h00028193);
write_debug_mem(11'h01C, 32'hFFF18193);
write_debug_mem(11'h01D, 32'hFE019EE3);
write_debug_mem(11'h01E, 32'h00108093);
write_debug_mem(11'h01F, 32'h00F0F093);
write_debug_mem(11'h020, 32'hFFF90913);
write_debug_mem(11'h021, 32'hFE0910E3);
write_debug_mem(11'h022, 32'h00110113);
write_debug_mem(11'h023, 32'hF81FF06F);
write_debug_mem(11'h024, 32'h00100093);  // Mode 1: Knight Rider
write_debug_mem(11'h025, 32'h00600913);
write_debug_mem(11'h026, 32'h00182023);
write_debug_mem(11'h027, 32'h00028193);
write_debug_mem(11'h028, 32'hFFF18193);
write_debug_mem(11'h029, 32'hFE019EE3);
write_debug_mem(11'h02A, 32'h00109093);
write_debug_mem(11'h02B, 32'h00F0F093);
write_debug_mem(11'h02C, 32'hFFF90913);
write_debug_mem(11'h02D, 32'hFE0910E3);
write_debug_mem(11'h02E, 32'h00110113);
write_debug_mem(11'h02F, 32'hF51FF06F);
write_debug_mem(11'h030, 32'h00F00093);  // Mode 2: Blink all
write_debug_mem(11'h031, 32'h00600913);
write_debug_mem(11'h032, 32'h00182023);
write_debug_mem(11'h033, 32'h00028193);
write_debug_mem(11'h034, 32'hFFF18193);
write_debug_mem(11'h035, 32'hFE019EE3);
write_debug_mem(11'h036, 32'h00F0C093);
write_debug_mem(11'h037, 32'hFFF90913);
write_debug_mem(11'h038, 32'hFE0912E3);
write_debug_mem(11'h039, 32'h00110113);
write_debug_mem(11'h03A, 32'hF25FF06F);

// End of fast pattern memory initialization
