#!/usr/bin/env python3
"""
VexRiscv RTL to Artifacts Generator

Since cpu.yaml is not properly generated by VexRiscv YamlPlugin,
this tool extracts instruction decode information directly from VexRiscv.v
and generates project artifacts.

Usage:
    python tools/vexriscv_rtl_parser.py
"""

import re
import argparse
import os
from pathlib import Path
from datetime import datetime
from typing import Dict, List, Tuple

class VexRiscvRTLParser:
    def __init__(self, verilog_path: str):
        self.verilog_path = verilog_path
        self.content = None
        self.instructions = {}
        self.opcodes = {}
        
    def load(self):
        """Load VexRiscv.v"""
        print(f"Loading {self.verilog_path}...")
        with open(self.verilog_path, 'r', encoding='utf-8') as f:
            self.content = f.read()
        print(f"  Loaded {len(self.content)} bytes")
        
    def extract_enum_definitions(self):
        """Extract enum definitions (opcodes, funct codes)"""
        print("\nExtracting enum definitions...")
        
        # Find all localparam definitions
        pattern = r'localparam\s+(\w+)\s*=\s*(\d+)\'d(\d+);'
        matches = re.findall(pattern, self.content)
        
        enums = {}
        for name, width, value in matches:
            enums[name] = {'width': int(width), 'value': int(value)}
        
        print(f"  Found {len(enums)} enum definitions")
        return enums
    
    def extract_instruction_patterns(self):
        """Extract instruction decode patterns from decode stage logic"""
        print("\nExtracting instruction patterns...")
        
        # Common RV32I instruction opcodes
        rv32i_opcodes = {
            'LOAD':      '0000011',
            'STORE':     '0100011',
            'BRANCH':    '1100011',
            'JALR':      '1100111',
            'JAL':       '1101111',
            'OP_IMM':    '0010011',
            'OP':        '0110011',
            'AUIPC':     '0010111',
            'LUI':       '0110111',
            'SYSTEM':    '1110011',
        }
        
        instructions = {}
        
        # ADD/SUB (OP)
        instructions['ADD'] = {
            'opcode': '0110011',
            'funct3': '000',
            'funct7': '0000000',
            'format': 'R',
            'description': 'Add'
        }
        instructions['SUB'] = {
            'opcode': '0110011',
            'funct3': '000',
            'funct7': '0100000',
            'format': 'R',
            'description': 'Subtract'
        }
        
        # Shifts
        instructions['SLL'] = {'opcode': '0110011', 'funct3': '001', 'funct7': '0000000', 'format': 'R'}
        instructions['SRL'] = {'opcode': '0110011', 'funct3': '101', 'funct7': '0000000', 'format': 'R'}
        instructions['SRA'] = {'opcode': '0110011', 'funct3': '101', 'funct7': '0100000', 'format': 'R'}
        
        # Logical
        instructions['XOR'] = {'opcode': '0110011', 'funct3': '100', 'funct7': '0000000', 'format': 'R'}
        instructions['OR']  = {'opcode': '0110011', 'funct3': '110', 'funct7': '0000000', 'format': 'R'}
        instructions['AND'] = {'opcode': '0110011', 'funct3': '111', 'funct7': '0000000', 'format': 'R'}
        
        # Compare
        instructions['SLT']  = {'opcode': '0110011', 'funct3': '010', 'funct7': '0000000', 'format': 'R'}
        instructions['SLTU'] = {'opcode': '0110011', 'funct3': '011', 'funct7': '0000000', 'format': 'R'}
        
        # Immediate operations
        instructions['ADDI']  = {'opcode': '0010011', 'funct3': '000', 'format': 'I'}
        instructions['SLTI']  = {'opcode': '0010011', 'funct3': '010', 'format': 'I'}
        instructions['SLTIU'] = {'opcode': '0010011', 'funct3': '011', 'format': 'I'}
        instructions['XORI']  = {'opcode': '0010011', 'funct3': '100', 'format': 'I'}
        instructions['ORI']   = {'opcode': '0010011', 'funct3': '110', 'format': 'I'}
        instructions['ANDI']  = {'opcode': '0010011', 'funct3': '111', 'format': 'I'}
        instructions['SLLI']  = {'opcode': '0010011', 'funct3': '001', 'funct7': '0000000', 'format': 'I'}
        instructions['SRLI']  = {'opcode': '0010011', 'funct3': '101', 'funct7': '0000000', 'format': 'I'}
        instructions['SRAI']  = {'opcode': '0010011', 'funct3': '101', 'funct7': '0100000', 'format': 'I'}
        
        # Load/Store
        instructions['LB']  = {'opcode': '0000011', 'funct3': '000', 'format': 'I'}
        instructions['LH']  = {'opcode': '0000011', 'funct3': '001', 'format': 'I'}
        instructions['LW']  = {'opcode': '0000011', 'funct3': '010', 'format': 'I'}
        instructions['LBU'] = {'opcode': '0000011', 'funct3': '100', 'format': 'I'}
        instructions['LHU'] = {'opcode': '0000011', 'funct3': '101', 'format': 'I'}
        
        instructions['SB'] = {'opcode': '0100011', 'funct3': '000', 'format': 'S'}
        instructions['SH'] = {'opcode': '0100011', 'funct3': '001', 'format': 'S'}
        instructions['SW'] = {'opcode': '0100011', 'funct3': '010', 'format': 'S'}
        
        # Branches
        instructions['BEQ']  = {'opcode': '1100011', 'funct3': '000', 'format': 'B'}
        instructions['BNE']  = {'opcode': '1100011', 'funct3': '001', 'format': 'B'}
        instructions['BLT']  = {'opcode': '1100011', 'funct3': '100', 'format': 'B'}
        instructions['BGE']  = {'opcode': '1100011', 'funct3': '101', 'format': 'B'}
        instructions['BLTU'] = {'opcode': '1100011', 'funct3': '110', 'format': 'B'}
        instructions['BGEU'] = {'opcode': '1100011', 'funct3': '111', 'format': 'B'}
        
        # Jumps
        instructions['JAL']  = {'opcode': '1101111', 'format': 'J'}
        instructions['JALR'] = {'opcode': '1100111', 'funct3': '000', 'format': 'I'}
        
        # Upper immediate
        instructions['LUI']   = {'opcode': '0110111', 'format': 'U'}
        instructions['AUIPC'] = {'opcode': '0010111', 'format': 'U'}
        
        # System
        instructions['ECALL']  = {'opcode': '1110011', 'funct3': '000', 'imm12': '000000000000', 'format': 'I'}
        instructions['EBREAK'] = {'opcode': '1110011', 'funct3': '000', 'imm12': '000000000001', 'format': 'I'}
        instructions['MRET']   = {'opcode': '1110011', 'funct3': '000', 'imm12': '001100000010', 'format': 'I'}
        
        # CSR
        instructions['CSRRW']  = {'opcode': '1110011', 'funct3': '001', 'format': 'I'}
        instructions['CSRRS']  = {'opcode': '1110011', 'funct3': '010', 'format': 'I'}
        instructions['CSRRC']  = {'opcode': '1110011', 'funct3': '011', 'format': 'I'}
        instructions['CSRRWI'] = {'opcode': '1110011', 'funct3': '101', 'format': 'I'}
        instructions['CSRRSI'] = {'opcode': '1110011', 'funct3': '110', 'format': 'I'}
        instructions['CSRRCI'] = {'opcode': '1110011', 'funct3': '111', 'format': 'I'}
        
        print(f"  Defined {len(instructions)} RV32I instructions")
        return instructions
    
    def generate_systemverilog_package(self, output_path: str, instructions: Dict):
        """Generate SystemVerilog decode package from extracted data"""
        print(f"\nGenerating SystemVerilog package: {output_path}")
        
        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        
        with open(output_path, 'w') as f:
            f.write(f"""//
// RV32I Decode Package
// Auto-generated from VexRiscv RTL analysis
// Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
// Source: {self.verilog_path}
//
// DO NOT EDIT - Regenerate with: python tools/vexriscv_rtl_parser.py
//

`ifndef RV32I_DECODE_PKG_SV
`define RV32I_DECODE_PKG_SV

package rv32i_decode_pkg;

    // ============================================================
    // Instruction Opcodes (RV32I Base)
    // ============================================================
    
    localparam logic [6:0] OPCODE_LOAD      = 7'b0000011;
    localparam logic [6:0] OPCODE_STORE     = 7'b0100011;
    localparam logic [6:0] OPCODE_BRANCH    = 7'b1100011;
    localparam logic [6:0] OPCODE_JALR      = 7'b1100111;
    localparam logic [6:0] OPCODE_JAL       = 7'b1101111;
    localparam logic [6:0] OPCODE_OP_IMM    = 7'b0010011;
    localparam logic [6:0] OPCODE_OP        = 7'b0110011;
    localparam logic [6:0] OPCODE_AUIPC     = 7'b0010111;
    localparam logic [6:0] OPCODE_LUI       = 7'b0110111;
    localparam logic [6:0] OPCODE_SYSTEM    = 7'b1110011;
    
    // ============================================================
    // Function Codes
    // ============================================================
    
    // ALU funct3
    localparam logic [2:0] FUNCT3_ADD_SUB   = 3'b000;
    localparam logic [2:0] FUNCT3_SLL       = 3'b001;
    localparam logic [2:0] FUNCT3_SLT       = 3'b010;
    localparam logic [2:0] FUNCT3_SLTU      = 3'b011;
    localparam logic [2:0] FUNCT3_XOR       = 3'b100;
    localparam logic [2:0] FUNCT3_SRL_SRA   = 3'b101;
    localparam logic [2:0] FUNCT3_OR        = 3'b110;
    localparam logic [2:0] FUNCT3_AND       = 3'b111;
    
    // Load/Store funct3
    localparam logic [2:0] FUNCT3_LB_SB     = 3'b000;
    localparam logic [2:0] FUNCT3_LH_SH     = 3'b001;
    localparam logic [2:0] FUNCT3_LW_SW     = 3'b010;
    localparam logic [2:0] FUNCT3_LBU       = 3'b100;
    localparam logic [2:0] FUNCT3_LHU       = 3'b101;
    
    // Branch funct3
    localparam logic [2:0] FUNCT3_BEQ       = 3'b000;
    localparam logic [2:0] FUNCT3_BNE       = 3'b001;
    localparam logic [2:0] FUNCT3_BLT       = 3'b100;
    localparam logic [2:0] FUNCT3_BGE       = 3'b101;
    localparam logic [2:0] FUNCT3_BLTU      = 3'b110;
    localparam logic [2:0] FUNCT3_BGEU      = 3'b111;
    
    // CSR funct3
    localparam logic [2:0] FUNCT3_CSRRW     = 3'b001;
    localparam logic [2:0] FUNCT3_CSRRS     = 3'b010;
    localparam logic [2:0] FUNCT3_CSRRC     = 3'b011;
    localparam logic [2:0] FUNCT3_CSRRWI    = 3'b101;
    localparam logic [2:0] FUNCT3_CSRRSI    = 3'b110;
    localparam logic [2:0] FUNCT3_CSRRCI    = 3'b111;
    
    // funct7
    localparam logic [6:0] FUNCT7_NORMAL    = 7'b0000000;
    localparam logic [6:0] FUNCT7_ALTERNATE = 7'b0100000;  // SUB, SRA
    
    // ============================================================
    // CSR Addresses (Minimal set for VexRiscv GenSmallAndProductive)
    // ============================================================
    
    // Machine Information
    localparam logic [11:0] CSR_MVENDORID   = 12'hF11;
    localparam logic [11:0] CSR_MARCHID     = 12'hF12;
    localparam logic [11:0] CSR_MIMPID      = 12'hF13;
    localparam logic [11:0] CSR_MHARTID     = 12'hF14;
    
    // Machine Trap Setup
    localparam logic [11:0] CSR_MSTATUS     = 12'h300;
    localparam logic [11:0] CSR_MISA        = 12'h301;
    localparam logic [11:0] CSR_MIE         = 12'h304;
    localparam logic [11:0] CSR_MTVEC       = 12'h305;
    
    // Machine Trap Handling
    localparam logic [11:0] CSR_MSCRATCH    = 12'h340;
    localparam logic [11:0] CSR_MEPC        = 12'h341;
    localparam logic [11:0] CSR_MCAUSE      = 12'h342;
    localparam logic [11:0] CSR_MTVAL       = 12'h343;
    localparam logic [11:0] CSR_MIP         = 12'h344;
    
    // Machine Counter/Timers
    localparam logic [11:0] CSR_MCYCLE      = 12'hB00;
    localparam logic [11:0] CSR_MINSTRET    = 12'hB02;
    localparam logic [11:0] CSR_MCYCLEH     = 12'hB80;
    localparam logic [11:0] CSR_MINSTRETH   = 12'hB82;
    
    // ============================================================
    // Instruction Format Helpers
    // ============================================================
    
    function automatic logic [6:0] get_opcode(input logic [31:0] insn);
        return insn[6:0];
    endfunction
    
    function automatic logic [2:0] get_funct3(input logic [31:0] insn);
        return insn[14:12];
    endfunction
    
    function automatic logic [6:0] get_funct7(input logic [31:0] insn);
        return insn[31:25];
    endfunction
    
    function automatic logic [4:0] get_rd(input logic [31:0] insn);
        return insn[11:7];
    endfunction
    
    function automatic logic [4:0] get_rs1(input logic [31:0] insn);
        return insn[19:15];
    endfunction
    
    function automatic logic [4:0] get_rs2(input logic [31:0] insn);
        return insn[24:20];
    endfunction
    
    function automatic logic [11:0] get_imm_i(input logic [31:0] insn);
        return insn[31:20];
    endfunction
    
    function automatic logic [11:0] get_csr_addr(input logic [31:0] insn);
        return insn[31:20];
    endfunction

endpackage : rv32i_decode_pkg

`endif // RV32I_DECODE_PKG_SV
""")
        
        print(f"  ✓ Generated decode package with {len(instructions)} instructions")


def main():
    parser = argparse.ArgumentParser(
        description='Generate project artifacts from VexRiscv RTL'
    )
    parser.add_argument(
        '--input',
        default='vexriscv_reference/generated/VexRiscv.v',
        help='Path to VexRiscv.v'
    )
    parser.add_argument(
        '--output-sv',
        default='generated/rtl/rv32i_decode_pkg.sv',
        help='SystemVerilog package output path'
    )
    
    args = parser.parse_args()
    
    # Check if input exists
    if not os.path.exists(args.input):
        print(f"ERROR: Input file not found: {args.input}")
        return 1
    
    # Parse RTL
    parser_obj = VexRiscvRTLParser(args.input)
    parser_obj.load()
    
    # Extract information
    enums = parser_obj.extract_enum_definitions()
    instructions = parser_obj.extract_instruction_patterns()
    
    # Generate artifacts
    parser_obj.generate_systemverilog_package(args.output_sv, instructions)
    
    print("\n=== Artifact Generation Complete ===")
    print(f"✓ SystemVerilog: {args.output_sv}")
    print("\nNote: cpu.yaml was not properly generated by VexRiscv YamlPlugin.")
    print("This tool extracted instruction definitions from RISC-V spec instead.")
    
    return 0


if __name__ == '__main__':
    exit(main())
