#!/usr/bin/env python3
"""
VexRiscv cpu.yaml to Project Artifacts Generator

Parses cpu.yaml generated by VexRiscv and generates:
1. SystemVerilog decode package (generated/rtl/rv32i_decode_pkg.sv)
2. UVM instruction library (generated/uvm/rv32i_insn_library.svh)
3. Assembler encoding config (generated/asm/instruction_encoding.yaml)

Usage:
    python tools/yaml_to_artifacts.py
    python tools/yaml_to_artifacts.py --input vexriscv_reference/generated/cpu.yaml
"""

import yaml
import argparse
import os
from pathlib import Path
from datetime import datetime
from typing import Dict, List, Any

class VexRiscvYAMLParser:
    def __init__(self, yaml_path: str):
        self.yaml_path = yaml_path
        self.data = None
        self.instructions = {}
        self.csrs = {}
        
    def load(self):
        """Load and parse cpu.yaml"""
        print(f"Loading {self.yaml_path}...")
        with open(self.yaml_path, 'r') as f:
            self.data = yaml.safe_load(f)
        
        # Extract instruction decode table
        if 'instructionDecodes' in self.data:
            for insn_data in self.data['instructionDecodes']:
                name = insn_data.get('name', 'UNKNOWN')
                self.instructions[name] = insn_data
        
        # Extract CSR addresses
        if 'csrMapAllocations' in self.data:
            for csr_data in self.data['csrMapAllocations']:
                name = csr_data.get('name', 'UNKNOWN')
                self.csrs[name] = csr_data
                
        print(f"  Found {len(self.instructions)} instructions")
        print(f"  Found {len(self.csrs)} CSRs")
        
    def generate_systemverilog_package(self, output_path: str):
        """Generate SystemVerilog decode package"""
        print(f"\nGenerating SystemVerilog package: {output_path}")
        
        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        
        with open(output_path, 'w') as f:
            f.write(f"""//
// RV32I Decode Package
// Auto-generated from VexRiscv cpu.yaml
// Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
// Source: {self.yaml_path}
//
// DO NOT EDIT - Regenerate with: python tools/yaml_to_artifacts.py
//

`ifndef RV32I_DECODE_PKG_SV
`define RV32I_DECODE_PKG_SV

package rv32i_decode_pkg;

    // ============================================================
    // Instruction Opcodes (from VexRiscv decoder)
    // ============================================================
    
""")
            
            # Generate opcode constants
            for name, data in sorted(self.instructions.items()):
                if 'encoding' in data:
                    encoding = data['encoding']
                    # Extract opcode bits
                    if isinstance(encoding, str):
                        # Parse encoding string like "0000000----------000-----0110011"
                        opcode_bits = encoding[-7:]  # Last 7 bits are opcode
                        if opcode_bits.replace('-', '').replace('0', '').replace('1', '') == '':
                            opcode_val = opcode_bits.replace('-', '0')
                            f.write(f"    localparam logic [6:0] OPCODE_{name.upper()} = 7'b{opcode_val};\n")
            
            f.write(f"""
    // ============================================================
    // Function Codes
    // ============================================================
    
""")
            
            # Generate funct3/funct7 constants
            for name, data in sorted(self.instructions.items()):
                if 'encoding' in data:
                    encoding = data['encoding']
                    if isinstance(encoding, str) and len(encoding) == 32:
                        # Extract funct7 [31:25]
                        funct7 = encoding[0:7]
                        # Extract funct3 [14:12]
                        funct3 = encoding[17:20]
                        
                        if funct3.replace('-', '').replace('0', '').replace('1', '') == '':
                            funct3_val = funct3.replace('-', '0')
                            f.write(f"    localparam logic [2:0] FUNCT3_{name.upper()} = 3'b{funct3_val};\n")
                        
                        if funct7.replace('-', '').replace('0', '').replace('1', '') == '':
                            funct7_val = funct7.replace('-', '0')
                            f.write(f"    localparam logic [6:0] FUNCT7_{name.upper()} = 7'b{funct7_val};\n")
            
            f.write(f"""
    // ============================================================
    // CSR Addresses (from VexRiscv CSR map)
    // ============================================================
    
""")
            
            # Generate CSR address constants
            for name, data in sorted(self.csrs.items()):
                if 'address' in data:
                    addr = data['address']
                    f.write(f"    localparam logic [11:0] CSR_{name.upper()} = 12'h{addr:03X};\n")
            
            f.write(f"""
    // ============================================================
    // Instruction Format Helpers
    // ============================================================
    
    function automatic logic [6:0] get_opcode(input logic [31:0] insn);
        return insn[6:0];
    endfunction
    
    function automatic logic [2:0] get_funct3(input logic [31:0] insn);
        return insn[14:12];
    endfunction
    
    function automatic logic [6:0] get_funct7(input logic [31:0] insn);
        return insn[31:25];
    endfunction
    
    function automatic logic [4:0] get_rd(input logic [31:0] insn);
        return insn[11:7];
    endfunction
    
    function automatic logic [4:0] get_rs1(input logic [31:0] insn);
        return insn[19:15];
    endfunction
    
    function automatic logic [4:0] get_rs2(input logic [31:0] insn);
        return insn[24:20];
    endfunction

endpackage : rv32i_decode_pkg

`endif // RV32I_DECODE_PKG_SV
""")
        
        print(f"  ✓ Generated {len(self.instructions)} instruction definitions")
        print(f"  ✓ Generated {len(self.csrs)} CSR definitions")
    
    def generate_uvm_library(self, output_path: str):
        """Generate UVM instruction sequence item library"""
        print(f"\nGenerating UVM library: {output_path}")
        
        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        
        with open(output_path, 'w') as f:
            f.write(f"""//
// RV32I UVM Instruction Library
// Auto-generated from VexRiscv cpu.yaml
// Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
// Source: {self.yaml_path}
//
// DO NOT EDIT - Regenerate with: python tools/yaml_to_artifacts.py
//

`ifndef RV32I_INSN_LIBRARY_SVH
`define RV32I_INSN_LIBRARY_SVH

import rv32i_decode_pkg::*;

// Base instruction class
class rv32i_insn_base extends uvm_sequence_item;
    rand bit [31:0] encoding;
    rand bit [4:0] rd, rs1, rs2;
    rand bit [11:0] imm12;
    rand bit [19:0] imm20;
    
    `uvm_object_utils_begin(rv32i_insn_base)
        `uvm_field_int(encoding, UVM_ALL_ON | UVM_HEX)
        `uvm_field_int(rd, UVM_ALL_ON)
        `uvm_field_int(rs1, UVM_ALL_ON)
        `uvm_field_int(rs2, UVM_ALL_ON)
    `uvm_object_utils_end
    
    function new(string name = "rv32i_insn_base");
        super.new(name);
    endfunction
    
    // Encode instruction
    virtual function bit [31:0] encode();
        return encoding;
    endfunction
endclass

// Instruction type classes generated from cpu.yaml
""")
            
            # Generate instruction classes
            for name, data in sorted(self.instructions.items()):
                class_name = f"rv32i_insn_{name.lower()}"
                f.write(f"""
class {class_name} extends rv32i_insn_base;
    `uvm_object_utils({class_name})
    
    function new(string name = "{class_name}");
        super.new(name);
    endfunction
    
    constraint c_encoding {{
        // Instruction: {name}
""")
                
                if 'encoding' in data and isinstance(data['encoding'], str):
                    encoding_str = data['encoding']
                    # Generate constraints based on encoding
                    f.write(f"        // Encoding pattern: {encoding_str}\n")
                
                f.write(f"""    }}
endclass
""")
            
            f.write(f"""
`endif // RV32I_INSN_LIBRARY_SVH
""")
        
        print(f"  ✓ Generated {len(self.instructions)} UVM instruction classes")
    
    def generate_assembler_config(self, output_path: str):
        """Generate assembler encoding configuration"""
        print(f"\nGenerating assembler config: {output_path}")
        
        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        
        asm_config = {
            'generated': datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
            'source': self.yaml_path,
            'instructions': {},
            'csrs': {}
        }
        
        # Convert instruction data
        for name, data in self.instructions.items():
            asm_config['instructions'][name] = {
                'encoding': data.get('encoding', ''),
                'format': data.get('format', 'UNKNOWN'),
                'stage': data.get('stage', 'UNKNOWN')
            }
        
        # Convert CSR data
        for name, data in self.csrs.items():
            asm_config['csrs'][name] = {
                'address': data.get('address', 0),
                'access': data.get('access', 'RW')
            }
        
        with open(output_path, 'w') as f:
            yaml.dump(asm_config, f, default_flow_style=False, sort_keys=True)
        
        print(f"  ✓ Generated assembler config")


def main():
    parser = argparse.ArgumentParser(
        description='Generate project artifacts from VexRiscv cpu.yaml'
    )
    parser.add_argument(
        '--input',
        default='vexriscv_reference/generated/cpu.yaml',
        help='Path to cpu.yaml (default: vexriscv_reference/generated/cpu.yaml)'
    )
    parser.add_argument(
        '--output-sv',
        default='generated/rtl/rv32i_decode_pkg.sv',
        help='SystemVerilog package output path'
    )
    parser.add_argument(
        '--output-uvm',
        default='generated/uvm/rv32i_insn_library.svh',
        help='UVM library output path'
    )
    parser.add_argument(
        '--output-asm',
        default='generated/asm/instruction_encoding.yaml',
        help='Assembler config output path'
    )
    
    args = parser.parse_args()
    
    # Check if input exists
    if not os.path.exists(args.input):
        print(f"ERROR: Input file not found: {args.input}")
        print("Generate VexRiscv RTL first: .\\tools\\build_vexriscv.ps1")
        return 1
    
    # Parse YAML
    parser_obj = VexRiscvYAMLParser(args.input)
    parser_obj.load()
    
    # Generate artifacts
    parser_obj.generate_systemverilog_package(args.output_sv)
    parser_obj.generate_uvm_library(args.output_uvm)
    parser_obj.generate_assembler_config(args.output_asm)
    
    print("\n=== Artifact Generation Complete ===")
    print(f"✓ SystemVerilog: {args.output_sv}")
    print(f"✓ UVM Library:   {args.output_uvm}")
    print(f"✓ Assembler:     {args.output_asm}")
    
    return 0


if __name__ == '__main__':
    exit(main())
