#!/usr/bin/env python3
"""
Generate minimal LED test - single loop with sequential writes.
Verifies LED MMIO functionality without complex branching.
"""

import sys
sys.path.insert(0, '..')

from encoder import RV32IInstructionEncoder

def generate_minimal_led_pattern(num_writes=6, delay_cycles=10):
    """
    Generate minimal LED test: sequential writes with simple loop.
    
    Args:
        num_writes: Number of LED values to write (default: 6)
        delay_cycles: Delay between writes (default: 10)
    
    Returns:
        List of RV32I instructions
    """
    enc = RV32IInstructionEncoder()
    instructions = []
    
    # ========== SETUP ==========
    # LED address: 0x407C
    instructions.append(enc.lui(15, 0x4))           # x15 = 0x4000
    instructions.append(enc.addi(16, 15, 0x7C))     # x16 = 0x407C (LED address)
    
    # Initialize pattern value
    instructions.append(enc.addi(1, 0, 1))          # x1 = 1 (start value)
    
    # Initialize loop counter
    instructions.append(enc.addi(18, 0, num_writes))  # x18 = num_writes
    
    # Delay constant
    instructions.append(enc.addi(5, 0, delay_cycles & 0x7FF))  # x5 = delay_cycles
    
    # ========== MAIN LOOP ==========
    loop_start_pc = len(instructions) * 4
    
    # Write LED value
    instructions.append(enc.sw(1, 16, 0))           # MEM[0x407C] = x1
    
    # Delay loop
    instructions.append(enc.addi(3, 5, 0))          # x3 = delay_cycles
    delay_loop_pc = len(instructions) * 4
    instructions.append(enc.addi(3, 3, -1))         # x3--
    instructions.append(enc.bne(3, 0, -4))          # Loop if x3 != 0
    
    # Increment pattern value
    instructions.append(enc.addi(1, 1, 1))          # x1++
    
    # Decrement loop counter
    instructions.append(enc.addi(18, 18, -1))       # x18--
    instructions.append(enc.bne(18, 0, loop_start_pc - (len(instructions) * 4 + 4)))  # Loop if x18 != 0
    
    # ========== END ==========
    instructions.append(enc.ebreak())                # EBREAK - signal completion
    
    return instructions


def main():
    """Generate SystemVerilog memory initialization file."""
    
    print("=" * 70)
    print("RV32I MINIMAL LED Test - SystemVerilog Memory Generator")
    print("*** SIMPLE SINGLE-LOOP VERIFICATION ***")
    print("=" * 70)
    print()
    
    # Generate instructions with ultra-fast delays for simulation
    num_writes = 6
    delay_cycles = 10
    
    print(f"Generating minimal LED test...")
    instructions = generate_minimal_led_pattern(num_writes, delay_cycles)
    
    print(f"Generated {len(instructions)} instructions")
    print(f"Program size: {len(instructions) * 4} bytes")
    print(f"Configuration:")
    print(f"  - LED writes: {num_writes}")
    print(f"  - Delay: {delay_cycles} cycles/write (~{delay_cycles * 8}ns @ 125MHz)")
    print(f"  - Total time: ~{num_writes * delay_cycles * 8}ns = ~{num_writes * delay_cycles * 8 / 1000:.2f}μs")
    print()
    
    # Generate output file
    import os
    output_path = "../../sim/tests/rv32i_minimal_led_mem.svh"
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    
    with open(output_path, 'w') as f:
        f.write("// Auto-generated by generate_minimal_led_test.py\n")
        f.write("// RV32I MINIMAL LED Test - Memory Initialization\n")
        f.write("//\n")
        f.write(f"// Total instructions: {len(instructions)}\n")
        f.write(f"// Program size: {len(instructions) * 4} bytes\n")
        f.write(f"// Configuration: {num_writes} LED writes, {delay_cycles} cycles/write\n")
        f.write("//\n")
        f.write("// Test purpose: Verify LED MMIO functionality\n")
        f.write("// Expected: Sequential writes (1→2→3→4→5→6)\n")
        f.write(f"// LED MMIO address: 0x0000_407C\n")
        f.write(f"// Simulation time needed: ~{num_writes * delay_cycles * 8 / 1000:.2f}μs\n")
        f.write("\n")
        f.write("// Instruction memory initialization (to be included in test task)\n")
        
        for idx, instr in enumerate(instructions):
            addr = idx
            f.write(f"write_debug_mem(11'h{addr:03X}, 32'h{instr:08X});\n")
    
    print(f"Generated: {output_path}")
    print()
    print("Usage in SystemVerilog test:")
    print("  virtual task load_pattern();")
    print('      `include "rv32i_minimal_led_mem.svh"')
    print("  endtask")
    print()
    print("=" * 70)


if __name__ == "__main__":
    main()
