#!/usr/bin/env python3
"""
Generate SystemVerilog Memory Initialization for FAST LED Pattern

This script generates a high-speed version of the complex pattern for simulation.
Delay reduced to 1000 cycles (~8μs @ 125MHz) to allow multiple LED changes
in a 100μs simulation window.

Output: rv32i_complex_pattern_mem_fast.svh
"""
import sys
import os

# Add parent directories to path
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', '..', '..'))
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', '..', '..', 'software'))

from rv32i.patterns import generate_led_complex_pattern_fast

def generate_sv_mem_init(output_file='rv32i_complex_pattern_mem_fast.svh'):
    """Generate SystemVerilog memory initialization file for fast simulation"""
    
    print("="*70)
    print("RV32I FAST Complex Pattern - SystemVerilog Memory Generator")
    print("*** OPTIMIZED FOR SHORT SIMULATIONS ***")
    print("="*70)
    
    # Generate the fast pattern program
    print("\nGenerating ULTRA-FAST complex pattern instructions...")
    instructions = generate_led_complex_pattern_fast(delay_cycles=10)
    
    print(f"Generated {len(instructions)} instructions")
    print(f"Program size: {len(instructions) * 4} bytes")
    print(f"Delay: 10 cycles/iteration (~80ns @ 125MHz)")
    print(f"Expected: 24 LED changes in ~2μs simulation")
    
    # Create SystemVerilog file
    output_path = os.path.join('E:\\Nautilus\\workspace\\fpgawork\\TD4UART\\sim\\tests', output_file)
    
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write("// Auto-generated by generate_fast_pattern_sv.py\n")
        f.write("// RV32I FAST Complex LED Pattern - Memory Initialization\n")
        f.write("//\n")
        f.write(f"// Total instructions: {len(instructions)}\n")
        f.write(f"// Program size: {len(instructions) * 4} bytes\n")
        f.write("// Mode: ULTRA-FAST SIMULATION (10 cycles/iteration = ~80ns @ 125MHz)\n")
        f.write("//\n")
        f.write("// Pattern modes (6 iterations each):\n")
        f.write("//   Mode 0: Binary counter (1→2→3→4→5→6)\n")
        f.write("//   Mode 1: Knight Rider (1→2→4→8→4→2)\n")
        f.write("//   Mode 2: Blink all (0xF ↔ 0x0, 6 toggles)\n")
        f.write("//   Mode 3: Alternating (0x5 ↔ 0xA, 6 toggles)\n")
        f.write("//\n")
        f.write("// LED MMIO address: 0x0000_407C\n")
        f.write("// Total pattern changes: 24 (4 modes × 6 iterations)\n")
        f.write("// Simulation time needed: ~2μs for full cycle\n")
        f.write("\n")
        f.write("// Instruction memory initialization (to be included in test task)\n")
        
        # Write each instruction as a memory write (inline format)
        for i, insn in enumerate(instructions):
            addr = i
            f.write(f"write_debug_mem(11'h{addr:03X}, 32'h{insn:08X});")
            
            # Add comments for key sections
            if i == 0:
                f.write("  // Setup: LED address")
            elif i == 10:
                f.write("  // Mode 3: Alternating pattern")
            elif i == 24:
                f.write("  // Mode 0: Binary counter")
            elif i == 36:
                f.write("  // Mode 1: Knight Rider")
            elif i == 48:
                f.write("  // Mode 2: Blink all")
            
            f.write("\n")
        
        f.write("\n")
        f.write("// End of fast pattern memory initialization\n")
    
    print(f"\nGenerated: {output_path}")
    print("\nUsage in SystemVerilog test:")
    print(f"  virtual task load_pattern();")
    print(f"      `include \"{output_file}\"")
    print(f"  endtask")
    print("\n" + "="*70)

if __name__ == "__main__":
    generate_sv_mem_init()
