#!/usr/bin/env python3
"""
Generate SystemVerilog Memory Initialization for Complex LED Pattern

This script generates the actual 83-instruction complex pattern program
as SystemVerilog memory write tasks that can be included in DSIM tests.

Output: rv32i_complex_pattern_mem.svh
Usage: Include in rv32i_led_complex_pattern_test.sv
"""
import sys
import os

# Add parent directories to path
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', '..', '..'))
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', '..', '..', 'software'))

from rv32i.patterns import generate_led_complex_pattern

def generate_sv_mem_init(output_file='rv32i_complex_pattern_mem.svh', fast_sim=False):
    """Generate SystemVerilog memory initialization file"""
    
    print("="*70)
    print("RV32I Complex Pattern - SystemVerilog Memory Generator")
    print("="*70)
    
    if fast_sim:
        print("\n[FAST SIMULATION MODE]")
        print("Using minimal delays (1000 cycles = 8μs @ 125MHz)")
        print("Multiple LED changes visible within 100μs")
    
    # Generate the complex pattern program
    print("\nGenerating complex pattern instructions...")
    instructions = generate_led_complex_pattern(delay_cycles=5000000, fast_sim=fast_sim)
    
    print(f"Generated {len(instructions)} instructions")
    print(f"Program size: {len(instructions) * 4} bytes")
    
    # Create SystemVerilog file
    output_path = os.path.join('E:\\Nautilus\\workspace\\fpgawork\\TD4UART\\sim\\tests', output_file)
    
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write("// Auto-generated by generate_complex_pattern_sv.py\n")
        f.write("// RV32I Complex LED Pattern - Memory Initialization\n")
        f.write("//\n")
        f.write(f"// Total instructions: {len(instructions)}\n")
        f.write(f"// Program size: {len(instructions) * 4} bytes\n")
        if fast_mode:
            f.write("// Mode: FAST SIMULATION (1000 cycles/iteration)\n")
        else:
            f.write("// Mode: NORMAL (5M cycles/iteration)\n")
        f.write("//\n")
        f.write("// Pattern modes:\n")
        f.write("//   Mode 0: Binary counter (0→15, 16 iterations)\n")
        f.write("//   Mode 1: Knight Rider (1→2→4→8→4→2→1, 30 iterations)\n")
        f.write("//   Mode 2: Blink all (0xF ↔ 0x0, 20 iterations)\n")
        f.write("//   Mode 3: Alternating (0x5 ↔ 0xA, 50 iterations)\n")
        f.write("//\n")
        f.write("// LED MMIO address: 0x0000_407C\n")
        f.write("// Delay per iteration: 5M cycles (40ms @ 125MHz)\n")
        f.write("\n")
        
        # Write task definition
        f.write("task load_complex_pattern_program();\n")
        f.write("    $display(\"  Loading 83-instruction complex LED pattern program...\");\n")
        f.write("    $display(\"  Program size: %0d instructions (%0d bytes)\", %d, %d);\n" % 
                (len(instructions), len(instructions) * 4, len(instructions), len(instructions) * 4))
        f.write("\n")
        
        # Write each instruction as a memory write
        for i, insn in enumerate(instructions):
            addr = i
            f.write(f"    write_insn_mem(11'h{addr:03X}, 32'h{insn:08X});")
            
            # Add comments every 10 instructions
            if i % 10 == 0:
                if i == 0:
                    f.write("  // Setup: LED address")
                elif i < 20:
                    f.write("  // Mode dispatch")
                elif i < 40:
                    f.write("  // Mode 3: Alternating pattern")
                elif i < 55:
                    f.write("  // Mode 0: Binary counter")
                elif i < 70:
                    f.write("  // Mode 1: Knight Rider")
                else:
                    f.write("  // Mode 2: Blink all")
            
            f.write("\n")
        
        f.write("\n")
        f.write("    $display(\"  Program loaded successfully\");\n")
        f.write("endtask\n")
        f.write("\n")
        
        # Write helper task for memory writes
        f.write("// Helper task: Write instruction to memory\n")
        f.write("task write_insn_mem(input logic [10:0] word_addr, input logic [31:0] data);\n")
        f.write("    // Store instruction in testbench memory array\n")
        f.write("    cpu_inst.instruction_memory[word_addr] = data;\n")
        f.write("endtask\n")
    
    print(f"\nGenerated: {output_path}")
    print("\nUsage in SystemVerilog test:")
    print(f"  `include \"{output_file}\"")
    print("  // In initial block:")
    print("  load_complex_pattern_program();")
    print("\n" + "="*70)

if __name__ == "__main__":
    import sys
    fast_sim = '--fast-sim' in sys.argv or '--fast' in sys.argv
    generate_sv_mem_init(fast_sim=fast_sim)
